import Foundation

enum ApiEndpoints {
    static let login = "login"
    static let getUserInfo = "getUserInfo"
    static let changePassword = "changepass"
    static let getBookshelf = "getBookshelf"
    static let getChapterList = "getChapterList"
    static let getBookContent = "getBookContent"
    static let saveBookProgress = "saveBookProgress"
    static let setBookSource = "setBookSource"
    static let getAllTts = "getalltts"
    static let getDefaultTts = "getDefaultTTS"
    static let addTts = "addtts"
    static let deleteTts = "deltts"
    static let saveTtsBatch = "savettss"
    static let importBookPreview = "importBookPreview"
    static let getReplaceRulesPage = "getReplaceRulesPage"
    static let getReplaceRules = "getReplaceRulesNew"
    static let addReplaceRule = "addReplaceRule"
    static let deleteReplaceRule = "delReplaceRule"
    static let toggleReplaceRule = "stopReplaceRules"
    static let saveReplaceRules = "saverules"
    static let getBookSourcesPage = "getBookSourcesPage"
    static let getBookSources = "getBookSourcesNew"
    static let saveBookSource = "saveBookSource"
    static let deleteBookSource = "delbookSource"
    static let toggleBookSource = "stopbookSource"
    static let getBookSourceDetail = "getbookSources"
    static let getExploreUrl = "getBookSourcesExploreUrl"
    static let exploreBook = "exploreBook"
    static let searchBook = "searchBook"
    static let saveBook = "saveBook"
    static let deleteBook = "deleteBook"
    static let clearAllRemoteCache = "clearAllRemoteCache"
    static let getRssSources = "getRssSourcess"
    static let stopRssSource = "stopRssSource"
    static let editRssSources = "editRssSources"
    static let deleteRssSource = "delRssSource"
}
